server:
    error:
        include-stacktrace: never
spring:
    application:
        name: spring-security-jwt
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: jdbc:mysql://localhost:3306/db_security_jwt?createDatabaseIfNotExist=true
        username: ${MYSQL_USERNAME}
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                boot:
                    allow_jdbc_metadata_access: false
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        show_sql: true
